### ISSUE TITLE
Test failures with ffmpeg 7.0

### ISSUE THREAD

**Issue by lfos** [OpenShot/libopenshot#964]
Running the test suite with 08d7f335 (Add compatibility with FFMPEG 7.0, 2024-05-08) and with ffmpeg 7.0, there seem to be several test failures:

```
The following tests FAILED:
	30 - Clip:verify parent Timeline (Failed)
	34 - Clip:time remapping (Failed)
	35 - Clip:resample_audio_8000_to_48000_reverse (Failed)
	92 - FrameMapper:resample_audio_48000_to_41000 (Failed)
	93 - FrameMapper:resample_audio_mapper (Failed)
	172 - Timeline:Multi-threaded Timeline Add/Remove Clip (Failed)
```

The failures themselves all look fairly similar and contain output such as
```
[SWR @ 0x7df3fcb2e380] Input channel layout "" is invalid or unsupported.
[SWR @ 0x7df3fcb2e380] Context has not been initialized
```

@eclipseo Any idea? Do you remember whether you manually ran the full test suite with ffmpeg 7.0 and with the final version of the changes proposed in PR #954?

It'd also be good to extend the GitHub workflows to run the build and full test suite with ffmpeg 7.0.

**Comment by VVD** [comment]
Is this fixed in 0.4.0?

Changelog for OpenShot 3.3 says:
`FFmpeg Compatibility: Upgraded support for newer FFmpeg versions ensures stability on modern systems.`
https://www.openshot.org/blog/2024/12/22/new_openshot_release_330/

**Comment by lfos** [comment]
I just checked. Not fixed. It looks like there still the same issues.

**Comment by VVD** [comment]
Probably this is not fixed.

**Comment by rathann** [comment]
> [@eclipseo](https://github.com/eclipseo) Any idea? Do you remember whether you manually ran the full test suite with ffmpeg 7.0 and with the final version of the changes proposed in PR [#954](https://github.com/OpenShot/libopenshot/pull/954)?
> 
> It'd also be good to extend the GitHub workflows to run the build and full test suite with ffmpeg 7.0.

Unfortunately, the test suite failures were silently ignored in our package builds, so @eclipseo did not catch this, sorry about that. The problem is, we have no H.264 decoding support out-of-the box in Fedora, so many of the tests are failing because the Sintel trailer video is encoded with H.264 and FFmpeg is unable to find any decoder for H.264 video. If you replaced the sample video with something encoded with an unencumbered codec like VP9 or AV1 (e.g. https://commons.wikimedia.org/wiki/File:Big_Buck_Bunny_Trailer_1080p.ogv), we could run the full suite. Regardless, I'm fixing our package so that we skip only the tests that fail due to missing H.264 codec. That way, we can at least catch some regressions.

**Comment by lfos** [comment]
@rathann - The error is not specific to Fedora. My original report was filed based on us noticing the errors when packaging OpenShot for Arch Linux. And #1007 seems to suggest the issue exists under Windows too when using ffmpeg 7.

It'd be great to have the tests fixed instead of having to selectively ignore tests.
